world_db_names = ["actors",
                  "cards",
                  "combats",
                  "drawings",
                  "fog",
                  "folders",
                  "items",
                  "journal",
                  "macros",
                  "messages",
                  "playlists",
                  "scenes",
                  "settings",
                  "tables",
                  "users"]